### ISSUE TITLE
Create Main Page and About Us Page

### ISSUE THREAD

**Issue by deeheber** [risachi/travel-project#12]
Add new pages to the master repo and make sure the basic page structure is set.

**Comment by risachi** [comment]
I'll take the about us page

**Comment by dogweather** [comment]
Here's how to link to a PR:

See #19

**Comment by risachi** [comment]
I'm pretty much done with the basic About Us template for now - I added in a few things but it can definitely be fleshed out more. I haven't closed this issue because I didn't create the main page and don't know the status of that...

**Comment by Randallonius** [comment]
main page is done. Are we happy with the background color for pages? I'm also open to changing color of navbar and footer.
