### ISSUE TITLE
Set up the data structure

### ISSUE THREAD

**Issue by risachi** [risachi/travel-project#3]
using objects and arrays

Activity name, location, hours, indoor-or-outdoor, tags

**Comment by deeheber** [comment]
Possible category ideas for activities:
1. Indoor/Outdoor
2. Family friendly
3. Intensity Level (high, med, low)
4. Cost (high, med, low)

**Comment by risachi** [comment]
I'm debating whether to keep "family friendly" or just have separate "children" and "adult" categories, because most items are family friendly but does a 5 year old really want to go to the art museum?

**Comment by deeheber** [comment]
Children/Adult is ok with me.
