### ISSUE TITLE
Refactor Resources Page

### ISSUE THREAD

**Issue by risachi** [risachi/travel-project#35]
We can pull the activities' names and URLs using the array of activities in setup.js - this will allow us to change information in just one place instead of having to remember to change it in two places.

This will probably involve these steps:
- [x] Add a `url` property to the Activity object
- [x] Add each activity's url to the activities array
- [x] Change `resources.html` to just create the list by looping over this array

**Comment by jacobshillman** [comment]
Oh sure!!  ...do it the SMART way!!  ;)

**Comment by risachi** [comment]
Aaaand done.
