### ISSUE TITLE
Test Deploying Site

### ISSUE THREAD

**Issue by risachi** [risachi/travel-project#36]
The requirements state that the site has to be online somewhere ... I think https://www.bitballoon.com would be a really good (easy) way to deploy the site.

Basically we need to just test getting it up on the web. We can wait on this until we're closer to being finished though.

**Comment by Randallonius** [comment]
I remember Mark mentioning that the site just needed to be "live" and the gh pages through github would be suffficient.

**Comment by jacobshillman** [comment]
&deployed to github, gh-pages.

http://risachi.github.io/travel-project/

**Comment by risachi** [comment]
Awesome, looks good :+1:

**Comment by jacobshillman** [comment]
Last version of gh-pages as of pull request:
https://github.com/risachi/travel-project/pull/40

Will try to keep it updated with master.  :)
