### ISSUE TITLE
Make Styling of Each Page Consistent

### ISSUE THREAD

**Issue by risachi** [risachi/travel-project#37]
Looking at the code, I've noticed a few inconsistencies. For example, on most pages we've linked all the fonts we're using, but on at least one of them I noticed they aren't there. The headers should all be the same, at the very least, except maybe on index.html.

**Comment by Randallonius** [comment]
I'm working on something a bit more stylish for the nav bars and header that we can use across all of the pages. I should have it finished by tomorrow.
