### ISSUE TITLE
<discussion> Merge JS files??

### ISSUE THREAD

**Issue by jacobshillman** [risachi/travel-project#48]
I'm in favor of putting all the JS into a single file. 

I'd like to merge the headerfooter.js into the setup.js for semantic and simplicity (easier to maintain fewer files).

John'd like to keep the gallery.js separate for maintainability/readability: I concur.

Any thoughts on merging the activities.js with setup.js?

I'm easy, either way. :)

**Comment by risachi** [comment]
I vote for keeping things in separate files for the different layers in the
app. So setup.js is purely the data access layer.

Activities and others build on top of it, so they should be separate.

The sword rule of thumb I've learned is that a file should only be a page
or two long at max.

Oh, and having more files means we can work in parallel with fewer merge
conflicts.

**Comment by jacobshillman** [comment]
We can do that!

:+1:
