### ISSUE TITLE
Relocate image gallery

### ISSUE THREAD

**Issue by jacobshillman** [risachi/travel-project#50]
...this'll make more sense after John's new work is pushed up...

The image gallery isn't making sense on the Welcome page, anymore, so we're (John and I) wondering where the group thinks we should put it.

John and I are thinking the Resources or Activities pages are good candidates.

What do you think??

**Comment by deeheber** [comment]
Sounds good to me. Either the resources or activities pages are fine by me. I'd prefer to put it on whichever page has less content.
