### ISSUE TITLE
Group Name?

### ISSUE THREAD

**Issue by jacobshillman** [risachi/travel-project#61]
We need a group name.

Any thoughts?

**Comment by deeheber** [comment]
I feel like going the extra cheesy route and suggesting "PDXperts."

**Comment by jacobshillman** [comment]
I'm upvoting Danielle's suggestion.

That's AWESOME!!

**Comment by Randallonius** [comment]
Not only is it the only suggestion but it is a darn good one so I am voting for that as well.

**Comment by Randallonius** [comment]
I added it into the about-us page so I am closing this issue!
