### ISSUE TITLE
make page persistent

### ISSUE THREAD

**Issue by Randallonius** [risachi/travel-project#62]
Should be easy to accomplish at the end. Just make site remember results?

**Comment by deeheber** [comment]
I agree. I think we should just use the saved options from the activities app page once everything is complete.

**Comment by deeheber** [comment]
The choices object within activities.js holds all of the currently selected radio buttons.

For example a possible combo within that object could be {isIndoor: true, intensity: medium, kidFriendly: false} etc.

**Comment by deeheber** [comment]
Added a button to clear out the local storage/reset the user options.  PR #82
