### ISSUE TITLE
make the site responsive?

### ISSUE THREAD

**Issue by Randallonius** [risachi/travel-project#64]

**Comment by deeheber** [comment]
Good catch! On reviewing the final project assignment up on Canvas, this does appear to be a part of the final grade:

> Good and proper use of CSS -- Clear, readable, and efficient styles -- Responsive layout on various screen sizes like desktop and mobile

**Comment by Randallonius** [comment]
This could take a bit of time actually...Looks like I will be working on this one tonight.

**Comment by Randallonius** [comment]
I'm coming along with this and should have it done by tomorrow. Thank you for working on that footer Lisa, it was showing fine on my mac but Jacob noticed it had issues on his windows laptop so I was planning on working on it but you beat me to it.

**Comment by Randallonius** [comment]
Thought I was done. I am not. I'll have one final pull request.
