### ISSUE TITLE
Add second page "that accepts and processes user input".

### ISSUE THREAD

**Issue by jacobshillman** [risachi/travel-project#65]
Per assignment.

**Comment by risachi** [comment]
Anybody have ideas about what we can do for this? @deeheber @Randallonius

**Comment by jacobshillman** [comment]
John and I were thinking inserting a dynamic contact us web form that puts
fields in depending on user input might work.

Sound OK?

**Comment by Randallonius** [comment]
Without going the cheesy route and doing something like asking their name and using it throughout the site I think that may be our best bet at this point. The tough part with the contact us form is processing the info.

**Comment by Randallonius** [comment]
Jacob and I just spoke about maybe having checkboxes at the top for e-mail, github and and linkedin and our information in each of our boxes will show accordingly for either one or all. In addition if they click e-mail we could have a form at the bottom. For our e-mail we could make up some fake e-mails such as @codefellows.com

**Comment by Randallonius** [comment]
If we could send Jacob our linkedin name that would be great or if you aren't comfortable with that on the website then we can just use a fake one for you.

**Comment by deeheber** [comment]
I sent my linkedin name to Jacob via slack.

**Comment by jacobshillman** [comment]
So, I've got it mostly functioning. It's not beautiful. ...but I leave that for someone more aesthetic than me (I'm more the ascetic type...).

I don't have social media info for Jonathon or Lisa, so that part's generic.

**Comment by risachi** [comment]
Thanks! For now, this is great.
I'll add my info in once I'm back in pdx, since I don't remember my logins :/

**Comment by jacobshillman** [comment]
Missing Social Media info for Jonathon and Lisa;
Needs better styling - my efashion sense leaves something to be desired...;
Figured out how to have text AND the cool little icons, so added that.

&done.
