### ISSUE TITLE
Single quote fix

### ISSUE THREAD

**Issue by dogweather** [risachi/travel-project#91]
Hey everyone, here's a small fix I noticed you can make:

Single quotes are specially displayed (as in _Portland’s_), which is very cool. We can make beautiful typography on the web. But, there's a better way to do it. The top line is your method (the 96 entity). The bottom two lines demonstrate the results of either of two ways I'd suggest changing these to:

<img width="502" alt="screen shot 2015-12-18 at 2 05 52 pm" src="https://cloud.githubusercontent.com/assets/150670/11908431/01008970-a591-11e5-97e7-4d96d4abe54f.png">

Here's the HTML which produced that output:

``` html
    <h2>Helpful links to Portland&#96;s Famous Attractions:</h2>                
    <h2>Helpful links to Portland&rsquo;s Famous Attractions:</h2>              
    <h2>Helpful links to Portland’s Famous Attractions:</h2>                    
```

The first line is from your code. The second and third lines are two different ways to improve it. 

The second line uses a **named character reference**, always a nice way to go because it's self-documenting. The `rsquo` means [right-side single quote](http://www.w3.org/wiki/Common_HTML_entities_used_for_typography).

The third line works because the web is now unicode, and you can enter unicode characters directly into your HTML, if your computer will let you.

**Comment by Randallonius** [comment]
I like it. Thank you for the suggestion and I will have it in my final responsive pull tonight.
